### ISSUE TITLE
Swift UI example?

### ISSUE THREAD

**Issue by ramondebruyn** [kewlbear/Python-iOS#1]
Hi @kewlbear,

Thank you for this incredible package! I've been struggling to find something like this for the last week.

Question: I have a large iOS app that's about 90% written to which I need to add this PythoKit-iOS functionality. Do you by any chance have an example of the example app written in UIKit, as opposed to SwiftUI?

Thanks again for putting together this package!

**Comment by kewlbear** [comment]
This package is not dependent on SwiftUI. You just need to call SetPythonHome() when your app starts.

**Comment by ramondebruyn** [comment]
Gotcha. Thanks @kewlbear!
