### ISSUE TITLE
App crashes in Testflight

### ISSUE THREAD

**Issue by flatninth** [kewlbear/Python-iOS#10]
Hello.

I've been able to successfully integrate it in my iOS project and works well in release mode. 
Bit, when I archive it and open it through Testflight the app crashes.
Error is "PythonKit Fatal error: Python library not found."

[My tries during 1 week]
I tried "Enable Bitcode" and "Strip Style" all yes or all no.
updated Python package  (update package)
PythonSupport.initialize() in appdelegate.wift
I read all issue in your project for python-ios, pythonkit ..

[My config]
Xcode 13.3.1
IOS14/15

How can I resolve this issue? 

Thank you.

**Comment by kewlbear** [comment]
See https://github.com/kewlbear/PythonPlayground/issues/2#issuecomment-835925337.

**Comment by flatninth** [comment]
I resolved it!

Deployment - Strip Style - Debugging Symbols
and Enable Bitcode (uncheck) for archieving.

Thank you!
