### ISSUE TITLE
Crash on iOS16

### ISSUE THREAD

**Issue by KodaKoder** [kewlbear/Python-iOS#14]
I get a crash on iOS16

#0	(null) in _assertionFailure(_:_:file:line:flags:) ()
#1	(null) in swift_unexpectedError ()
#2	(null) in specialized static PythonLibrary.loadSymbol<A>(name:legacyName:type:) ()
#3	(null) in specialized static PythonLibrary.loadSymbol<A>(name:legacyName:type:) ()
#4	(null) in one-time initialization function for Py_Initialize ()
#7	0x000000010044995c in Py_Initialize.unsafeMutableAddressor
#8	0x000000010044995c in PythonInterface.init() 

In debug I working, once archived and released it crashes

where I'm wrong ? :)
Thanks

**Comment by kewlbear** [comment]
Maybe this? https://github.com/kewlbear/Python-iOS/issues/10#issuecomment-1128391485

**Comment by KodaKoder** [comment]
Thanks solved! :)
