### ISSUE TITLE
able to run the project but not able to archive the project 

### ISSUE THREAD

**Issue by ninadkambli17** [kewlbear/Python-iOS#5]
Python-iOS/Sources/Symbols/Symbols.m:27:9: 'Python.h' file not found

**Comment by kewlbear** [comment]
I recommend you to use kivy-ios branch of this package.  I have already verified that branch has no issues with archiving and uploading to App Store.

You just need the following code after updating package dependency:

```
import PythonSupport
...
PythonSupport.initialize()
```

**Comment by ninadkambli17** [comment]
tried with kivy-ios. Found "import resources" is missing. It worked properly in the 
<img width="1143" alt="Screenshot 2021-04-19 at 4 08 32 PM" src="https://user-images.githubusercontent.com/23742346/115223531-83afce00-a129-11eb-9d9c-d1c87a91c75e.png">
playground but when I am building in my project it's showing "no such module resources"

**Comment by kewlbear** [comment]
Yeah, kivy-ios has different package structure.  Saw your issue on PythonPlayground project. I've fixed all issues there. Never mind Kivy-ios now.

**Comment by ninadkambli17** [comment]
yes used the main branch and I was able to upload the app on the app store for review!!!  @kewlbear thanks a lot for your support!!!
