### ISSUE TITLE
app is crashing in release varient 

### ISSUE THREAD

**Issue by ninadkambli17** [kewlbear/Python-iOS#6]
![WhatsApp Image 2021-05-04 at 9 23 54 AM](https://user-images.githubusercontent.com/23742346/117096720-8a744d00-ad87-11eb-964e-2fa341e15beb.jpeg)
it runs perfectly with debug scheme but crashes when scheme set to release

**Comment by kewlbear** [comment]
https://github.com/kewlbear/PythonPlayground/issues/2
